<a href="https://colab.research.google.com/github/chakravartulavinay/Unp_sir_notes/blob/main/Copy_of_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# File Input/Output

Introduction to File Input/Output

- File I/O allows reading and writing data to external files.
- Python provides built-in functions and methods for file I/O operations.
- File I/O is essential for tasks such as reading data from a file, writing data to a file, or modifying existing files.

## Reading from a File

To read data from a file, follow these steps:

1. Open the file using the `open()` function.
2. Use the `.read()` method to read the contents of the file.
3. Close the file using the `.close()` method.

Example:

```python
file = open('data.txt', 'r')
content = file.read()
file.close()
print(content)
```

In [ ]:
file = open('data.txt', 'r')
content = file.read()
file.close()
print(content)

## Writing to a File

To write data to a file, follow these steps:

1. Open the file in write mode using the `open()` function with the 'w' parameter.
2. Use the `.write()` method to write data to the file.
3. Close the file using the `.close()` method.

Example:

```python
file = open('output.txt', 'w')
file.write('Hello, World!')
file.close()
```

In [ ]:
file = open('output.txt', 'w')
file.write('Hello, World!')
file.close()

## Appending to a File

To append data to an existing file, follow these steps:

1. Open the file in append mode using the `open()` function with the 'a' parameter.
2. Use the `.write()` method to append data to the file.
3. Close the file using the `.close()` method.

Example:

```python
file = open('log.txt', 'a')
file.write('New log entry\n')
file.close()
```

In [ ]:
file = open('log.txt', 'a')
file.write('New log entry\n')
file.close()

1. Reading from a file:
To read data from a file in Python, you can use the `open()` function with the mode set to `'r'` (read). The `open()` function returns a file object, and you can use various methods to read data from it, such as `read()`, `readline()`, or `readlines()`.

Syntax:
```python
file = open('filename.txt', 'r')
# Perform read operations on the file
file.close()
```

Example:
Suppose you have a file named "data.txt" with the following content:
```
Hello, this is line 1.
And this is line 2.
```

```python
# Reading from a file
file = open('data.txt', 'r')

# Read the entire content at once
content = file.read()
print(content)

file.close()
```

Output:
```
Hello, this is line 1.
And this is line 2.
```

2. Writing to a file:
To write data to a file in Python, you can use the `open()` function with the mode set to `'w'` (write). This will create a new file if it doesn't exist or truncate the existing file. You can use the `write()` method to write data to the file.

Syntax:
```python
file = open('filename.txt', 'w')
# Perform write operations on the file
file.close()
```

Example:
```python
# Writing to a file
file = open('output.txt', 'w')

file.write('This is line 1.\n')
file.write('And this is line 2.\n')

file.close()
```

Output (in the "output.txt" file):
```
This is line 1.
And this is line 2.
```

3. Appending to a file:
To append data to an existing file in Python, you can use the `open()` function with the mode set to `'a'` (append). This will create a new file if it doesn't exist or add new content to the end of the existing file. You can use the `write()` method to append data to the file.

Syntax:
```python
file = open('filename.txt', 'a')
# Perform append operations on the file
file.close()
```

Example:
Suppose you have an existing file named "data.txt" with the following content:
```
This is line 1.
```

```python
# Appending to a file
file = open('data.txt', 'a')

file.write('This is line 2.\n')
file.write('And this is line 3.\n')

file.close()
```

After running the above code, the "data.txt" file will contain:
```
This is line 1.
This is line 2.
And this is line 3.
```

Remember to always close the file after performing file operations using the `close()` method to release system resources and avoid potential data loss or corruption.

Note: An even better way to handle file operations is by using the `with` statement, as it automatically closes the file for you after the block of code is executed. Here's an example:

```python
# Reading from a file using 'with' statement
with open('data.txt', 'r') as file:
    content = file.read()
    print(content)

# Writing to a file using 'with' statement
with open('output.txt', 'w') as file:
    file.write('This is line 1.\n')
    file.write('And this is line 2.\n')

# Appending to a file using 'with' statement
with open('data.txt', 'a') as file:
    file.write('This is line 2.\n')
    file.write('And this is line 3.\n')
```

Using the `with` statement is a recommended approach for file handling in Python as it ensures proper file handling and exception handling.

Sure! I'll provide simplified code examples for some of the use cases mentioned earlier. Please note that the code examples are simplified to illustrate the concepts and may not include error handling or advanced features typically required in real-world applications.

1. **Reading and Processing Data Files (CSV):**

```python
import csv

# Reading data from a CSV file and calculating average grades
with open('student_data.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    next(reader)  # Skip header row
    total_grades = 0
    num_students = 0

    for row in reader:
        grade = int(row[2])  # Assuming grade is in the third column
        total_grades += grade
        num_students += 1

    if num_students > 0:
        average_grade = total_grades / num_students
        print(f"Average Grade: {average_grade:.2f}")
    else:
        print("No data found.")
```

2. **Storing User Information (Text File):**

```python
# User registration and storage in a text file
username = input("Enter username: ")
password = input("Enter password: ")

with open('users.txt', 'a') as file:
    file.write(f"{username},{password}\n")
```


3. **Handling Large Datasets:**

```python
# Reading and processing a large dataset in chunks
with open('large_dataset.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    next(reader)  # Skip header row

    chunk_size = 1000
    while True:
        chunk = [next(reader) for _ in range(chunk_size)]
        if not chunk:
            break

        # Process the chunk of data
        process_chunk(chunk)
```

4. **Creating Reports and Documents (Using f-strings):**

```python
# Creating a dynamic report
name = "John Doe"
age = 30
score = 85

report = f"Student Name: {name}\nAge: {age}\nScore: {score}"
with open('report.txt', 'w') as file:
    file.write(report)
```

These examples demonstrate some of the practical applications of file handling in Python for various use cases. Keep in mind that real-world implementations may require additional error handling, data validation, and other considerations to ensure robustness and security.

# Error Handling and Exception Handling

Introduction to Error Handling and Exception Handling

- Errors and exceptions can occur during program execution.
- Exception handling allows us to gracefully handle and recover from errors.
- Python provides a `try-except` block to catch and handle exceptions.

Example:

```python
try:
    # Code that might raise an exception
    result = 10 / 0
except ZeroDivisionError:
    print('Error: Cannot divide by zero')
```

In [ ]:
try:
    result = 10 / 0
except ZeroDivisionError:
    print('Error: Cannot divide by zero')

## Handling Multiple Exceptions

Handling Multiple Exceptions

- Multiple exceptions can be handled using multiple `except` blocks.
- Each `except` block specifies the type of exception to handle.

Example:

```python
try:
    # Code that might raise an exception
    result = 10 / 0
except ZeroDivisionError:
    print('Error: Cannot divide by zero')
except ValueError:
    print('Error: Invalid value')
```

In [ ]:
try:
    result = 10 / 0
except ZeroDivisionError:
    print('Error: Cannot divide by zero')
except ValueError:
    print('Error: Invalid value')

The `try` and `except` blocks in Python are used to implement error handling or exception handling. They allow you to handle potential errors or exceptions that might occur during the execution of a block of code. By using a `try` block, you can specify the code that might raise an exception, and the `except` block defines the code to be executed if an exception occurs.

The syntax for `try` and `except` blocks is as follows:

```python
try:
    # Code that might raise an exception
    # ...
except ExceptionType:
    # Code to handle the exception
    # ...
```

Here's a detailed explanation of the components of the `try` and `except` blocks:

1. `try` block:
   - The `try` block contains the code that may raise an exception. It is the part of the code that you want to protect from errors.
   - When the code inside the `try` block encounters an exception, the flow of execution immediately jumps to the corresponding `except` block without executing the rest of the code in the `try` block.

2. `except` block:
   - The `except` block defines the code that should be executed if an exception occurs in the `try` block. It handles the exception.
   - The `except` block must be indented and starts with the keyword `except` followed by the type of exception it handles.
   - You can specify the type of exception you want to catch after the `except` keyword, for example, `except ValueError` or `except FileNotFoundError`.
   - If you don't specify any exception type (using just `except:` without specifying the exception), it will catch all exceptions, but it is generally not recommended as it may hide unexpected errors.

3. `ExceptionType`:
   - `ExceptionType` refers to the specific type of exception that you want to catch. It can be any built-in exception class or a custom exception that you have defined.
   - If the code inside the `try` block raises an exception of the specified type, the corresponding `except` block will be executed.
   - If the exception raised does not match the type specified in the `except` block, it will not be caught, and the program may terminate with an unhandled exception.

Here's an example to illustrate the usage of `try` and `except` blocks:

```python
try:
    num1 = int(input("Enter a number: "))
    num2 = int(input("Enter another number: "))
    result = num1 / num2
    print(f"Result: {result}")
except ValueError:
    print("Please enter valid integers.")
except ZeroDivisionError:
    print("Cannot divide by zero.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
```

In this example:
- The code inside the `try` block attempts to get two integers from the user and perform division.
- If the user enters invalid inputs (non-integer values), a `ValueError` will be raised and caught by the first `except` block.
- If the user enters zero as the second number, a `ZeroDivisionError` will be raised and caught by the second `except` block.
- If any other unexpected error occurs, it will be caught by the generic `Exception` block, displaying a generic error message with the actual exception information.

By using `try` and `except` blocks, you can gracefully handle errors and exceptions in your code, preventing unexpected program termination and providing meaningful feedback to users. It's essential to handle specific exceptions when you know how to recover from them and use a more generic `Exception` block for any unanticipated errors that may occur.

# Introduction to NumPy

NumPy (Numerical Python) is a powerful library for numerical computations in Python.
It provides support for large, multi-dimensional arrays and matrices.
NumPy is widely used in scientific computing, data analysis, and machine learning.



NumPy, short for Numerical Python, is a powerful library for numerical and scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, as well as a wide range of mathematical functions to operate on these arrays. NumPy is widely used in various fields such as data science, machine learning, engineering, and scientific research.

Here's a brief explanation of NumPy's key features and benefits:

1. **N-dimensional Arrays (ndarrays):**

   NumPy's primary data structure is the `ndarray`, which stands for N-dimensional array. These arrays are homogeneous and allow you to store elements of the same data type. They are highly efficient and allow fast operations on large datasets.

2. **Mathematical Operations:**
   NumPy provides a vast collection of mathematical functions that can be applied to entire arrays, making it convenient to perform element-wise operations without using loops. This is known as vectorization, and it significantly improves performance.

3. **Broadcasting:**
   NumPy supports broadcasting, which allows operations between arrays of different shapes and sizes, making it easier to handle arrays of different dimensions.

4. **Indexing and Slicing:**
   NumPy offers powerful indexing and slicing capabilities, similar to Python lists, but with more flexibility to work with multi-dimensional arrays.

5. **Random Number Generation:**
   NumPy includes functions to generate random numbers, which are useful for simulations, testing, and various statistical applications.

6. **Integration with C/C++ and Fortran:**
   NumPy provides tools to integrate with existing C/C++ and Fortran code, making it a great choice for scientific applications with legacy codebases.

7. **Efficient Memory Usage:**
   NumPy's arrays are more memory-efficient compared to Python lists, as they are stored in contiguous blocks of memory.

8. **Linear Algebra Operations:**
   NumPy offers an extensive set of linear algebra functions, such as matrix operations, eigenvalues, eigenvectors, and more.

You can import NumPy and start using its features in your code:

```python
import numpy as np

# Creating a 1-dimensional NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Performing element-wise operations
result = arr + 10
print(result)  # Output: [11 12 13 14 15]

# Generating a 2-dimensional array
matrix = np.array([[1, 2], [3, 4]])

# Matrix multiplication
product = np.dot(matrix, matrix)
print(product)  # Output: [[ 7 10]
                #          [15 22]]
```

NumPy's intuitive syntax and powerful array operations make it an essential library for data manipulation, numerical computations, and scientific computing in Python. It forms the foundation of many other Python libraries used in data science and machine learning, such as Pandas and scikit-learn.

# NumPy Arrays

NumPy arrays are homogeneous, multi-dimensional data structures.
They can be created using the np.array() function.
Arrays have a fixed size and a specific shape, which can be accessed using the .shape attribute.

Example:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)         # Output: [1 2 3 4 5]
print(arr.shape)   # Output: (5,)
```



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr) # Output: [1 2 3 4 5]
print(type(arr))
print(arr.shape)   # Output: (5,)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(matrix.shape)

(2, 3)


In [ ]:
m = np.array([[1,2],[3,4]])
print("Matrix: \n")
print(m)
print(" \n")
r = m @ m # Shortcut for matrix mult.
# r = np.dot(m, m)
print("After Mult: m x m \n")
print(r)

Matrix: 

[[1 2]
 [3 4]]
 

After Mult: m x m 

[[ 7 10]
 [15 22]]


# Indexing and Slicing NumPy Arrays

NumPy arrays can be indexed and sliced similar to Python lists.
Indexing starts at 0, and negative indices count from the end of the array.
Slicing allows us to extract specific parts of an array.

Example:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])         # Output: 1
print(arr[-1])        # Output: 5
print(arr[1:4])       # Output: [2 3 4]
```



In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])         # Output: 1
print(arr[-1])        # Output: 5
print(arr[1:4])       # Output: [2 3 4]

1
5
[2 3 4]


In [ ]:
data = np.array(
    [[1, 200, 3, 4, 17],
      [166, 4, 30, 4, 5],
      [71, 20, 6, 4, 12],
      [61, 9, 3, 0, 5],
      [1050, 20, 9, 4, 1000]]
                )

In [ ]:
data.shape

(5, 5)

In [ ]:
print(data)

[[   1  200    3    4   17]
 [ 166    4   30    4    5]
 [  71   20    6    4   12]
 [  61    9    3    0    5]
 [1050   20    9    4 1000]]


In [ ]:
# I want 1-3 row and 2-4 column

data_sliced = data[:4,1:4]
print(data_sliced)

[[200   3   4]
 [  4  30   4]
 [ 20   6   4]
 [  9   3   0]]


# NumPy Array Operations (continued)

NumPy provides a wide range of mathematical and logical operations on arrays.
These operations can be performed element-wise or across entire arrays.
Let's explore some commonly used NumPy operations:



# Mathematical Operations

NumPy supports various mathematical operations on arrays, such as addition, subtraction, multiplication, and division.
These operations can be performed element-wise between two arrays or between an array and a scalar value.

Example:
```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print(result)  # Output: [5 7 9]

result = arr1 * 2
print(result)  # Output: [2 4 6]
```



# Statistical Functions

NumPy provides a wide range of statistical functions to analyze data in arrays.
These functions allow us to compute measures such as mean, median, standard deviation, and more.

Example:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

mean = np.mean(arr)
print(mean)  # Output: 3.0

median = np.median(arr)
print(median)  # Output: 3.0

std = np.std(arr)
print(std)  # Output: 1.4142135623730951
```



In [ ]:
data = np.array(
    [[1, 200, 3, 4, 17],
      [166, 4, 30, 4, 5],
      [71, 20, 6, 4, 12],
      [61, 9, 3, 0, 5],
      [1050, 20, 9, 4, 1000],
     [1770, 120, 29, 45, 9000]]
                )
print("mean accross columns and rows: ", np.mean(data), "\n") # Add all elements / num of elements

print("shape of data: ", data.shape[0], "rows", data.shape[1], "columns \n")

print(data)

mean accross columns and rows:  455.73333333333335 

shape of data:  6 rows 5 columns 

[[   1  200    3    4   17]
 [ 166    4   30    4    5]
 [  71   20    6    4   12]
 [  61    9    3    0    5]
 [1050   20    9    4 1000]
 [1770  120   29   45 9000]]


In [ ]:
print("Taking the mean accross rows \n")
mean = np.mean(data, axis = 0)
print("shape of mean: ", mean.shape)
print(mean)

Taking the mean accross rows 

shape of mean:  (5,)
[ 519.83333333   62.16666667   13.33333333   10.16666667 1673.16666667]


In [ ]:
print("Taking the mean across columns \n")
mean = np.mean(data, axis = 1)
print("shape of mean: ", mean.shape)
print(mean)

Taking the mean across columns 

shape of mean:  (6,)
[  45.    41.8   22.6   15.6  416.6 2192.8]


# Array Comparison and Logical Operations

NumPy enables us to perform element-wise comparisons between arrays.
Logical operations such as AND, OR, and NOT can also be applied to arrays.

Example:
```python
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 4])

greater_than = arr1 > arr2
print(greater_than)  # Output: [False False False]

logical_and = np.logical_and(arr1 > 1, arr2 < 3)
print(logical_and)  # Output: [False  True False]
```



# Array Aggregation Functions

NumPy provides functions to aggregate arrays by computing a single value from the entire array.
These functions include sum, min, max, and more.

Example:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

sum = np.sum(arr)
print(sum)  # Output: 15

min_val = np.min(arr)
print(min_val)  # Output: 1

max_val = np.max(arr)
print(max_val)  # Output: 5
```



# Array Reshaping and Transposition

NumPy allows us to reshape arrays using the .reshape() method.
Transposition can be performed using the .T attribute or the np.transpose() function.

Example:
```python
import numpy asnp

arr = np.array([[1, 2, 3], [4, 5, 6]])

reshaped = arr.reshape((3, 2))
print(reshaped)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

transposed = arr.T
print(transposed)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]
```



# Universal Functions (ufunc)

Universal Functions (ufunc) in NumPy are functions that operate element-wise on arrays.
They provide fast, vectorized operations and support a wide range of mathematical computations.

Example:
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

squared = np.square(arr)
print(squared)  # Output: [ 1  4  9 16 25]

exponential = np.exp(arr)
print(exponential)  # Output: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
```



# Matrix Multiplication and Linear Regression

Matrix multiplication is a fundamental operation in linear algebra and has practical applications, such as in linear regression.
Linear regression is a statistical modeling technique that explores the relationship between independent variables and a dependent variable.



# Matrix Multiplication

Matrix multiplication involves multiplying corresponding elements of rows and columns to produce a new matrix.
In NumPy, matrix multiplication can be performed using the np.dot() function or the @ operator.

Example:
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(result)
# Output:
# [[19 22]
#  [43 50]]
```



# Linear Regression and Matrix Multiplication

In linear regression, matrix multiplication is used to calculate the predicted values based on input features and their corresponding coefficients.
The equation for simple linear regression can be represented using matrix multiplication: y = X @ theta, where X is the input matrix and theta is the coefficient matrix.

Example:
```python
import numpy as np

X = np.array([[1, 3], [2, 4], [5, 6]])  # Input features
theta = np.array([[2], [3]])            # Coefficients

y = X @ theta
print(y)
# Output:
# [[11]
#  [16]
#  [28]]
```



# Summary and Next Steps

In Class 4, we covered various topics, including File Input/Output, Error Handling and Exception Handling, and NumPy operations, including array manipulation and matrix multiplication.
File I/O is essential for reading and writing data to external files.
Exception handling allows us to handle and recover from errors during program execution.
NumPy provides a wide range of operations for working with arrays, including mathematical operations, statistical functions, array manipulation, and matrix multiplication.
